# Generated by Django 4.2.8 on 2023-12-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlaceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("attribute1", models.BooleanField()),
                ("attribute2", models.BooleanField()),
                ("attribute3", models.BooleanField()),
                ("attribute4", models.BooleanField()),
                ("attribute5", models.BooleanField()),
                ("attribute6", models.BooleanField()),
                ("attribute7", models.BooleanField()),
                ("attribute8", models.BooleanField()),
                ("attribute9", models.BooleanField()),
                ("attribute10", models.BooleanField()),
                ("attribute11", models.BooleanField()),
                ("attribute12", models.BooleanField()),
                ("attribute13", models.BooleanField()),
                ("attribute14", models.BooleanField()),
                ("attribute15", models.BooleanField()),
                ("attribute16", models.CharField(max_length=255)),
                ("attribute17", models.CharField(max_length=255)),
                ("attribute18", models.CharField(max_length=255)),
            ],
        ),
    ]
