# Generated by Django 4.2.8 on 2024-07-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrestaurant",
            name="place_course",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="savedrestaurant",
            name="place_latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="savedrestaurant",
            name="place_longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
